#!/usr/bin/env python3
from pathlib import Path
import sys,re
if len(sys.argv)!=2: raise SystemExit('usage: jobs-jobcore-patch.py ROOT')
root=Path(sys.argv[1])
js_path=root/'jobs.js'; suite_path=root/'enterprise-suite.js'; html_path=root/'job-core.html'
js=js_path.read_text(); suite=suite_path.read_text(); html=html_path.read_text()
repls={
'id="ec-name" value="Sample print job"':'id="ec-name" placeholder="e.g. Gallery launch prints"',
'id="ec-rev" value="R1"':'id="ec-rev" placeholder="e.g. R1"',
'id="ec-qty" min="1" type="number" value="500"':'id="ec-qty" min="1" type="number" placeholder="e.g. 500"',
'id="ec-size" value="210 × 297 mm"':'id="ec-size" placeholder="e.g. 210 × 297 mm"',
'id="ec-material" value="Coated stock"':'id="ec-material" placeholder="e.g. coated stock"',
'<textarea id="ec-note">Initial production baseline</textarea>':'<textarea id="ec-note" placeholder="Revision note (optional)"></textarea>'
}
for a,b in repls.items():
 if a not in html: raise SystemExit('missing job-core fragment '+a)
 html=html.replace(a,b)
js=js.replace("const KEY = 'print-prep-lab-jobs-v1';", "const KEY = 'print-prep-lab-jobs-v1';\n  const SELECTED_KEY = 'print-prep-lab-selected-job-id-v1';")
js=js.replace("function write(){try{localStorage.setItem(KEY,JSON.stringify(jobs));return true}catch{return false}}", "function write(){try{localStorage.setItem(KEY,JSON.stringify(jobs));return true}catch{return false}}\n  function selectedId(){const v=safeJSON(SELECTED_KEY,null);return typeof v==='string'?v:null}\n  function selectJob(id){try{localStorage.setItem(SELECTED_KEY,JSON.stringify(id));return true}catch{return false}}")
old="return `<article class=\"card\" data-id=\"${esc(j.id)}\"><div class=\"job-top\"><div><span class=\"kicker\">${esc(j.priority||'Normal')} priority</span><h3>${esc(j.name||'Untitled job')}</h3></div><span class=\"badge\">${done}/${STAGES.length} stages</span></div><p>${esc(j.product||'Product not set')}${j.provider?` · ${esc(j.provider)}`:''}</p><div class=\"job-meta\"><div><small>Quantity</small><b>${Number(j.quantity||1).toLocaleString()}</b></div><div><small>Due</small><b>${j.due?esc(j.due):'Not set'}</b></div><div><small>Readiness</small><b>${pct}%</b></div></div><div class=\"pipeline\">${STAGES.map(([k,l])=>`<button type=\"button\" class=\"step ${j.stages?.[k]?'done':(next?.[0]===k?'current':'')}\" data-stage=\"${k}\" title=\"Toggle ${l}\">${l}</button>`).join('')}</div>${j.notes?`<p>${esc(j.notes)}</p>`:''}<div class=\"job-actions\">${next?`<a class=\"btn primary\" href=\"${linkFor(next[0],j)}\">Next: ${next[1]}</a>`:'<span class=\"btn primary\" aria-label=\"All stages marked complete\">Ready for sign-off</span>'}<a class=\"btn\" href=\"/studio?job=${encodeURIComponent(j.name||'')}&provider=${encodeURIComponent(j.provider||'')}\">Studio</a><button class=\"btn\" type=\"button\" data-snapshot>Refresh snapshot</button><button class=\"btn danger\" type=\"button\" data-delete>Delete</button></div></article>`;"
new="const selected=selectedId()===j.id;return `<article class=\"card${selected?' selected-job':''}\" data-id=\"${esc(j.id)}\"><div class=\"job-top\"><div><span class=\"kicker\">${esc(j.priority||'Normal')} priority${selected?' · Selected':''}</span><h3>${esc(j.name||'Untitled job')}</h3></div><span class=\"badge\">${done}/${STAGES.length} stages</span></div><p>${esc(j.product||'Product not set')}${j.provider?` · ${esc(j.provider)}`:''}</p><div class=\"job-meta\"><div><small>Quantity</small><b>${Number(j.quantity||1).toLocaleString()}</b></div><div><small>Due</small><b>${j.due?esc(j.due):'Not set'}</b></div><div><small>Readiness</small><b>${pct}%</b></div></div><div class=\"pipeline\">${STAGES.map(([k,l])=>`<button type=\"button\" class=\"step ${j.stages?.[k]?'done':(next?.[0]===k?'current':'')}\" data-stage=\"${k}\" title=\"Toggle ${l}\">${l}</button>`).join('')}</div>${j.notes?`<p>${esc(j.notes)}</p>`:''}<div class=\"job-actions\">${next?`<a class=\"btn primary\" href=\"${linkFor(next[0],j)}\">Next: ${next[1]}</a>`:'<span class=\"btn primary\" aria-label=\"All stages marked complete\">Ready for sign-off</span>'}<button class=\"btn\" type=\"button\" data-select>${selected?'Selected':'Select job'}</button><a class=\"btn\" href=\"/job-core\">Job Core</a><a class=\"btn\" href=\"/studio?job=${encodeURIComponent(j.name||'')}&provider=${encodeURIComponent(j.provider||'')}\">Studio</a><button class=\"btn\" type=\"button\" data-snapshot>Refresh snapshot</button><button class=\"btn danger\" type=\"button\" data-delete>Delete</button></div></article>`;"
if old not in js: raise SystemExit('jobs render fragment not found')
js=js.replace(old,new)
js=js.replace("write(); $('job-create').reset(); $('jc-qty').value=1; renderJobs();", "selectJob(jobs[jobs.length-1].id);write(); $('job-create').reset(); $('jc-qty').value=1; renderJobs();",1)
needle="const card=e.target.closest('[data-id]'); if(!card)return; const j=jobs.find(x=>x.id===card.dataset.id); if(!j)return;\n    const stage=e.target.closest('[data-stage]');"
rep="const card=e.target.closest('[data-id]'); if(!card)return; const j=jobs.find(x=>x.id===card.dataset.id); if(!j)return;\n    if(e.target.closest('[data-select]')){selectJob(j.id);renderJobs();return}\n    const stage=e.target.closest('[data-stage]');"
if needle not in js: raise SystemExit('jobs click fragment not found')
js=js.replace(needle,rep)
js=js.replace("if(e.target.closest('[data-delete]')){jobs=jobs.filter(x=>x.id!==j.id);write();renderJobs()}", "if(e.target.closest('[data-delete]')){const wasSelected=selectedId()===j.id;jobs=jobs.filter(x=>x.id!==j.id);write();if(wasSelected)localStorage.removeItem(SELECTED_KEY);renderJobs()}")
start=suite.find('function jobCore(){'); end=suite.find('\nfunction digitalTwin(){',start)
if start<0 or end<0: raise SystemExit('jobCore block not found')
jobcore=r'''function jobCore(){const KEY='enterprise-job-core-v1',REV='enterprise-job-revisions-v1',MAP='enterprise-job-cores-v2',SELECTED='selected-job-id-v1',JOBS='jobs-v1';
function jobs(){const v=C.read(JOBS,[]);return Array.isArray(v)?v.filter(Boolean):[]}
function selected(){const x=C.read(SELECTED,null);return typeof x==='string'?x:null}
function cores(){const v=C.read(MAP,{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function legacyIntoMap(map){const old=C.read(KEY,null);if(old&&typeof old==='object'){const id=String(old.jobId||old.id||'');if(id&&!map[id])map[id]={...old,jobId:id,id:id}}return map}
function deriveFromJob(j){return {schema:'ppl-enterprise-job',version:2,jobId:j.id,id:j.id,name:j.name||'',revision:'',quantity:Number(j.quantity)||1,trim:'',material:'',deadline:j.due||'',note:'',updatedAt:C.now()}}
function active(){let map=legacyIntoMap(cores()),id=selected(),list=jobs();if(!id&&list.length===1)id=list[0].id;if(id){const j=list.find(x=>x.id===id);return map[id]||(j?deriveFromJob(j):null)}return null}
function fill(cur){$('ec-name').value=cur?.name||'';$('ec-rev').value=cur?.revision||'';$('ec-qty').value=cur?.quantity||'';$('ec-size').value=cur?.trim||'';$('ec-material').value=cur?.material||'';$('ec-deadline').value=cur?.deadline||'';$('ec-note').value=cur?.note||''}
function render(){const cur=active(),rs=C.read(REV,[]),id=selected(),list=jobs(),job=list.find(x=>x.id===id);fill(cur);$('ec-output').innerHTML=(job?row(`Selected job: ${job.name||'Untitled job'}`,`ID ${job.id}`,'SELECTED','good'):row('No job selected','Choose a job from Jobs before editing Job Core, or save a standalone Job Core.','EMPTY','warn'))+(cur?row(cur.name||'Untitled job',`${cur.revision||'No revision'} · qty ${cur.quantity||'—'} · ${cur.trim||'Trim not set'}`,'CURRENT','good'):'')+rs.slice().reverse().filter(r=>!id||r.jobId===id||r.id===id).slice(0,8).map(r=>row(r.revision||'Revision',`${String(r.at||'').slice(0,16).replace('T',' ')} · ${r.note||'no note'}`,'SNAPSHOT','warn')).join('')}
function save(){const list=jobs(),selectedId=selected(),selectedJob=list.find(x=>x.id===selectedId),map=legacyIntoMap(cores()),prev=(selectedId&&map[selectedId])||active(),id=selectedId||prev?.jobId||prev?.id||C.id(),cur={schema:'ppl-enterprise-job',version:2,jobId:id,id:id,name:$('ec-name').value.trim()||selectedJob?.name||'Untitled job',revision:$('ec-rev').value.trim()||'R1',quantity:Math.max(1,n('ec-qty')||Number(selectedJob?.quantity)||1),trim:$('ec-size').value.trim(),material:$('ec-material').value.trim(),deadline:$('ec-deadline').value||selectedJob?.due||'',note:$('ec-note').value.trim(),updatedAt:C.now()};let changed=[];if(prev)for(const k of ['quantity','trim','material','deadline'])if(String(prev[k]??'')!==String(cur[k]??''))changed.push(k);cur.invalidates=[...new Set(changed.flatMap(k=>k==='quantity'?['capacity','costing','stock','packaging']:k==='trim'?['preflight','imposition','costing']:k==='material'?['costing','provider','qa']:['timeline','capacity','risk']))];map[id]=cur;C.write(MAP,map);C.write(KEY,cur);C.write(SELECTED,id);const rs=C.read(REV,[]);rs.push({...cur,at:C.now(),changed});C.write(REV,rs.slice(-100));if(selectedJob){selectedJob.name=cur.name;selectedJob.quantity=cur.quantity;selectedJob.due=cur.deadline||selectedJob.due||'';selectedJob.updatedAt=C.now();C.write(JOBS,list)}render()}
$('ec-save').onclick=save;$('ec-export').onclick=()=>C.download('print-prep-job.json',active()||{});document.addEventListener('ppl:job-selected',render);render()}'''
suite=suite[:start]+jobcore+suite[end:]
html_path.write_text(html); js_path.write_text(js); suite_path.write_text(suite)
print('Patched Jobs/Job Core selection and non-destructive per-job persistence')
