from pathlib import Path
import re, sys
p=Path(sys.argv[1])
s=p.read_text(encoding='utf-8')
old_prefix='(()=>{\'use strict\';const C=window.PPLCore,$=id=>document.getElementById(id),mode=document.body.dataset.enterpriseMode,n=id=>Number($(id)?.value)||0,esc=s=>C.safeText(s),row=(title,note,status=\'INFO\',cls=\'warn\')=>`<div class="ep-row"><div><b>${esc(title)}</b><small>${esc(note)}</small></div><span class="ep-status ${cls}">${esc(status)}</span></div>`;\nconst signalEntries=()=>Object.entries(C.allSignals());const blockedWord=s=>/BLOCK|HOLD|FAIL|LATE|OVERDUE|REORDER|SHORT|CRITICAL/i.test(JSON.stringify(s||\'\'));const okayWord=s=>/READY|PASS|APPROV|FEASIBLE|MATCH|GOOD|OK/i.test(JSON.stringify(s||\'\'));\n'
new_prefix='(()=>{\'use strict\';const C=window.PPLCore,R=window.PPLStatusRules,$=id=>document.getElementById(id),mode=document.body.dataset.enterpriseMode,n=id=>Number($(id)?.value)||0,esc=s=>C.safeText(s),row=(title,note,status=\'INFO\',cls=\'warn\')=>`<div class="ep-row"><div><b>${esc(title)}</b><small>${esc(note)}</small></div><span class="ep-status ${cls}">${esc(status)}</span></div>`;\nif(!R)return;const decisionRow=(title,d)=>row(title,d.reason,R.badge(d.state),R.cls(d.state));\n'
if not s.startswith(old_prefix): raise SystemExit('Phase2a patch: enterprise-suite prefix did not match expected baseline')
s=new_prefix+s[len(old_prefix):]
pat='function digitalTwin\\(\\)\\{.*?\\}\\n(?=function supplier\\(\\))'
repl="function digitalTwin(){function run(){const sources=R.global(C.allSignals()),blocked=sources.filter(x=>x.result.state===R.S.BLOCK),open=sources.filter(x=>x.result.state!==R.S.PASS),allNoData=sources.length&&sources.every(x=>x.result.state===R.S.NO_DATA),health=blocked.length?'BLOCKED':!sources.length||allNoData?'NO DATA':open.length?'REVIEW':'CLEAR';$('dt-signals').textContent=sources.length;$('dt-blockers').textContent=blocked.length;$('dt-health').textContent=health;const rows=(blocked.length?blocked:open).slice(0,12);$('dt-list').innerHTML=rows.length?rows.map(x=>decisionRow(R.label(x.kind),x.result)).join(''):health==='CLEAR'?row(R.tr('No explicit decision blocker is recorded','لا يوجد مانع قرار صريح مسجل'),R.tr('All stored decision sources recognized by this view passed their own checks. This is not a release approval.','كل مصادر القرار المحفوظة التي يتعرف عليها هذا العرض اجتازت فحوصها الخاصة. هذا لا يُعد اعتمادًا للإطلاق.'),'CLEAR','good'):row(R.tr('No decision evidence is saved yet','لا توجد أدلة قرار محفوظة بعد'),R.tr('Use the specialist modules to save evidence before interpreting production health.','استخدم الوحدات المتخصصة لحفظ الأدلة قبل تفسير صحة الإنتاج.'),'NO DATA','warn')} $('dt-refresh').onclick=run;document.addEventListener('ppl:language-applied',run);run()}"+"\n"
s,n=re.subn(pat,lambda m:repl,s,count=1,flags=re.S)
if n!=1: raise SystemExit('Phase2a patch: failed to replace digitalTwin (count=%s)'%n)
pat='function releaseCenter\\(\\)\\{.*?\\}\\n(?=function automation\\(\\))'
repl="function releaseCenter(){let packet=null;function run(){const s=C.allSignals(),checks=[['job',R.pick(s,'job',['enterprise-job-core-v1'])],['preflight',R.pick(s,'preflight',['preflight-signal-v1','preflight-last-v1'])],['approvals',R.pick(s,'approvals',['approval-summary-v1','approvals-v1'])],['qa',R.pick(s,'qa',['qa-summary-v1','qa-history-v1'])],['supplier',R.pick(s,'supplier',['supplier-intelligence-last-v1'])]],decisions=checks.map(([kind,x])=>({kind,...x,result:R.evaluate(kind,x.value)})),blocked=decisions.filter(x=>x.result.state===R.S.BLOCK),open=decisions.filter(x=>x.result.state!==R.S.PASS),status=blocked.length?'HOLD':open.length?'REVIEW':'READY';$('rc-status').textContent=status;$('rc-gates').textContent=decisions.length;$('rc-blockers').textContent=blocked.length;$('rc-list').innerHTML=decisions.map(x=>decisionRow(R.label(x.kind),x.result)).join('');packet={schema:'ppl-release-center-packet',version:3,generatedAt:C.now(),status,checks:decisions.map(x=>({name:R.label(x.kind),key:x.key,state:x.result.state,reason:x.result.reason})),job:s['enterprise-job-core-v1']||null};C.write('release-center-last-v2',packet)}$('rc-build').onclick=run;$('rc-download').onclick=()=>packet&&C.download('print-prep-release-packet-v2.json',packet);document.addEventListener('ppl:language-applied',run);run()}"+"\n"
s,n=re.subn(pat,lambda m:repl,s,count=1,flags=re.S)
if n!=1: raise SystemExit('Phase2a patch: failed to replace releaseCenter (count=%s)'%n)
pat='function enterpriseDashboard\\(\\)\\{.*?\\}\\n(?=function readiness\\(\\))'
repl="function enterpriseDashboard(){function run(){const s=C.allSignals(),jobs=s['jobs-v1']||[],sources=R.global(s),blocked=sources.filter(x=>x.result.state===R.S.BLOCK),open=sources.filter(x=>x.result.state!==R.S.PASS);$('ed-jobs').textContent=Array.isArray(jobs)?jobs.length:0;$('ed-signals').textContent=sources.length;$('ed-blockers').textContent=blocked.length;const rows=(blocked.length?blocked:open).slice(0,15);$('ed-list').innerHTML=rows.length?rows.map(x=>decisionRow(R.label(x.kind),x.result)).join(''):sources.length?row(R.tr('No explicit decision blocker is recorded','لا يوجد مانع قرار صريح مسجل'),R.tr('Recognized stored sources passed their own checks. Run Readiness Audit for the required release evidence.','المصادر المحفوظة المعروفة اجتازت فحوصها الخاصة. شغّل تدقيق الجاهزية لأدلة الإصدار المطلوبة.'),'CLEAR','good'):row(R.tr('No decision evidence is saved yet','لا توجد أدلة قرار محفوظة بعد'),R.tr('Run the specialist modules before interpreting this dashboard.','شغّل الوحدات المتخصصة قبل تفسير هذه اللوحة.'),'NO DATA','warn')} $('ed-refresh').onclick=run;document.addEventListener('ppl:language-applied',run);run()}"+"\n"
s,n=re.subn(pat,lambda m:repl,s,count=1,flags=re.S)
if n!=1: raise SystemExit('Phase2a patch: failed to replace enterpriseDashboard (count=%s)'%n)
pat='function readiness\\(\\)\\{.*?\\}\\n(?=function command\\(\\))'
repl="function readiness(){function run(){const s=C.allSignals(),checks=[];if($('ra-preflight').checked)checks.push(['preflight',R.pick(s,'preflight',['preflight-signal-v1','preflight-last-v1'])]);if($('ra-approval').checked)checks.push(['approvals',R.pick(s,'approvals',['approval-summary-v1','approvals-v1'])]);if($('ra-qa').checked)checks.push(['qa',R.pick(s,'qa',['qa-summary-v1','qa-history-v1'])]);if($('ra-risk').checked)checks.push(['risk',R.pick(s,'risk',['risk-summary-v1','risk-register-v1'])]);if($('ra-stock').checked)checks.push(['stock',R.pick(s,'stock',['stock-last-v1'])]);if($('ra-provider').checked)checks.push(['supplier',R.pick(s,'supplier',['supplier-intelligence-last-v1'])]);const decisions=checks.map(([kind,x])=>({kind,...x,result:R.evaluate(kind,x.value)})),blocked=decisions.filter(x=>x.result.state===R.S.BLOCK),open=decisions.filter(x=>x.result.state!==R.S.PASS),status=blocked.length?'HOLD':decisions.length&&open.length===0?'READY':'REVIEW';$('ra-status').textContent=status;$('ra-required').textContent=decisions.length;$('ra-open').textContent=open.length;$('ra-list').innerHTML=decisions.map(x=>decisionRow(R.label(x.kind),x.result)).join('')||row(R.tr('No checks selected','لم يتم تحديد فحوص'),R.tr('Select at least one evidence category before interpreting readiness.','حدد فئة أدلة واحدة على الأقل قبل تفسير الجاهزية.'),'REVIEW','warn');C.write('readiness-audit-last-v1',{schema:'ppl-readiness-audit',version:2,updatedAt:C.now(),status,required:decisions.length,unresolved:open.map(x=>R.label(x.kind)),decisions:decisions.map(x=>({kind:x.kind,key:x.key,state:x.result.state,reason:x.result.reason}))})}$('ra-run').onclick=run;document.addEventListener('ppl:language-applied',run);run()}"+"\n"
s,n=re.subn(pat,lambda m:repl,s,count=1,flags=re.S)
if n!=1: raise SystemExit('Phase2a patch: failed to replace readiness (count=%s)'%n)
pat='function command\\(\\)\\{.*?\\}\\n(?=const handlers=)'
repl="function command(){function run(){const s=C.allSignals(),audit=s['readiness-audit-last-v1'],next=s['automation-next-action-v1'],sources=R.global(s),blockers=sources.filter(x=>x.result.state===R.S.BLOCK),auditDecision=R.evaluate('audit',audit),jobDecision=R.evaluate('job',s['enterprise-job-core-v1']);$('pc-signals').textContent=sources.length;$('pc-next').textContent=blockers.length||auditDecision.state===R.S.BLOCK?R.tr('Resolve blockers','حل العوائق'):auditDecision.state!==R.S.PASS?R.tr('Complete evidence','استكمل الأدلة'):next?.action||R.tr('Run readiness audit','شغّل تدقيق الجاهزية');$('pc-list').innerHTML=decisionRow(R.label('audit'),auditDecision)+decisionRow(R.label('job'),jobDecision)+row(R.tr('Known decision blockers','موانع القرار المعروفة'),blockers.length?R.tr(`${blockers.length} recognized source${blockers.length===1?' has':'s have'} a real blocker.`,`${blockers.length} مصدر معروف يحتوي مانعًا حقيقيًا.`):R.tr('No recognized stored source has a real blocker. Absence of a blocker is not release approval.','لا يوجد مصدر محفوظ معروف يحتوي مانعًا حقيقيًا. غياب المانع لا يعني اعتماد الإصدار.'),blockers.length?'BLOCK':'CLEAR',blockers.length?'bad':'good');C.write('command-center-last-v1',{schema:'ppl-command-center',version:101,updatedAt:C.now(),signalCount:sources.length,audit:audit||null,blockerSources:blockers.map(x=>x.key),nextAction:$('pc-next').textContent})}$('pc-refresh').onclick=run;document.addEventListener('ppl:language-applied',run);run()}"+"\n"
s,n=re.subn(pat,lambda m:repl,s,count=1,flags=re.S)
if n!=1: raise SystemExit('Phase2a patch: failed to replace command (count=%s)'%n)
if 'blockedWord' in s or 'okayWord' in s: raise SystemExit('Phase2a patch: legacy textual decision scan remains')
p.write_text(s,encoding='utf-8')
print('Phase2a patched enterprise-suite.js with explicit status consumers')
