#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv)!=5:
    raise SystemExit('usage: phase2c-jobs-patch.py ENTERPRISE_SUITE JOBS_JS JOBS_HTML JOB_CORE_HTML')
suite_p,jobs_js_p,jobs_html_p,core_html_p=map(Path,sys.argv[1:])
suite=suite_p.read_text(encoding='utf-8')
jobs=jobs_js_p.read_text(encoding='utf-8')
jobs_html=jobs_html_p.read_text(encoding='utf-8')
core_html=core_html_p.read_text(encoding='utf-8')

def block(text,start,end,new):
    a=text.find(start); b=text.find(end,a)
    if a<0 or b<0: raise SystemExit(f'marker not found: {start} / {end}')
    return text[:a]+new+text[b:]

job_core=r'''function jobCore(){const KEY='enterprise-job-core-v1',CORES='enterprise-job-cores-v2',REV='enterprise-job-revisions-v1',SELECTED='selected-job-id-v1',JOBS='jobs-v1';
const selectedId=()=>C.read(SELECTED,null),allJobs=()=>{const x=C.read(JOBS,[]);return Array.isArray(x)?x:[]},selectedJob=()=>allJobs().find(j=>j&&j.id===selectedId())||null,allCores=()=>{const x=C.read(CORES,[]);return Array.isArray(x)?x:[]};
function setField(id,value){const el=$(id);if(el)el.value=value??''}
function load(){const sid=selectedId(),job=selectedJob(),cores=allCores(),stored=sid?cores.find(x=>x&&x.jobId===sid):null,legacy=C.read(KEY,null),cur=stored||(sid?null:legacy);if(sid&&job){setField('ec-name',cur?.name||job.name||'');setField('ec-rev',cur?.revision||'');setField('ec-qty',cur?.quantity??job.quantity??'');setField('ec-size',cur?.trim||'');setField('ec-material',cur?.material||'');setField('ec-deadline',cur?.deadline||job.due||'');setField('ec-note','');$('ec-selected-job').innerHTML=`<b>Selected job:</b> ${esc(job.name||'Untitled job')} <small>(${esc(sid)})</small>`;$('ec-selected-job').className='ep-note good'}else if(sid&&!job){for(const id of ['ec-name','ec-rev','ec-qty','ec-size','ec-material','ec-deadline','ec-note'])setField(id,'');$('ec-selected-job').innerHTML='<b>Selected job is unavailable.</b> Return to Jobs and choose an existing record.';$('ec-selected-job').className='ep-note bad'}else if(cur){setField('ec-name',cur.name||'');setField('ec-rev',cur.revision||'');setField('ec-qty',cur.quantity??'');setField('ec-size',cur.trim||'');setField('ec-material',cur.material||'');setField('ec-deadline',cur.deadline||'');setField('ec-note','');$('ec-selected-job').innerHTML='<b>Legacy standalone Job Core.</b> Select a job in Jobs to link future revisions by ID.';$('ec-selected-job').className='ep-note warn'}else{for(const id of ['ec-name','ec-rev','ec-qty','ec-size','ec-material','ec-deadline','ec-note'])setField(id,'');$('ec-selected-job').innerHTML='<b>No job selected.</b> Choose a job in Jobs, or save a standalone Job Core if you intentionally do not need a portfolio link.';$('ec-selected-job').className='ep-note warn'}render()}
function render(){const sid=selectedId(),cur=sid?allCores().find(x=>x&&x.jobId===sid):C.read(KEY,null),rs=C.read(REV,[]).filter(r=>!sid||r.jobId===sid);$('ec-output').innerHTML=(cur?row(cur.name,`${cur.revision||'Unlabelled revision'} · qty ${cur.quantity} · ${cur.trim||'trim not set'}`,'CURRENT','good'):'')+rs.slice().reverse().slice(0,8).map(r=>row(r.revision||'Revision',`${String(r.at||'').slice(0,16).replace('T',' ')} · ${r.note||'no note'}`,'SNAPSHOT','warn')).join('')}
function save(){const sid=selectedId(),job=selectedJob(),cores=allCores(),previous=sid?cores.find(x=>x&&x.jobId===sid):C.read(KEY,null),qtyRaw=Number($('ec-qty').value),qty=Number.isFinite(qtyRaw)&&qtyRaw>0?Math.round(qtyRaw):null,name=$('ec-name').value.trim(),rev=$('ec-rev').value.trim();if(!name||!qty){$('ec-output').innerHTML=row('Job Core not saved','Enter a job name and a positive quantity.','INVALID','bad');return}const cur={schema:'ppl-enterprise-job',version:2,id:previous?.id||C.id(),jobId:sid||previous?.jobId||null,name,revision:rev||'R1',quantity:qty,trim:$('ec-size').value.trim(),material:$('ec-material').value.trim(),deadline:$('ec-deadline').value,note:$('ec-note').value.trim(),updatedAt:C.now()};let changed=[];if(previous)for(const k of ['quantity','trim','material','deadline'])if(String(previous[k]??'')!==String(cur[k]??''))changed.push(k);cur.invalidates=[...new Set(changed.flatMap(k=>k==='quantity'?['capacity','costing','stock','packaging']:k==='trim'?['preflight','imposition','costing']:k==='material'?['costing','provider','qa']:['timeline','capacity','risk']))];if(sid){const next=cores.filter(x=>x&&x.jobId!==sid);next.push(cur);C.write(CORES,next);if(job){const list=allJobs(),target=list.find(x=>x&&x.id===sid);if(target){target.name=cur.name;target.quantity=cur.quantity;target.due=cur.deadline;target.updatedAt=C.now();C.write(JOBS,list)}}}C.write(KEY,cur);const rs=C.read(REV,[]);rs.push({...cur,at:C.now(),changed});C.write(REV,rs.slice(-200));setField('ec-note','');render()}
$('ec-save').onclick=save;$('ec-export').onclick=()=>C.download('print-prep-job.json',selectedId()?allCores().find(x=>x&&x.jobId===selectedId())||{}:C.read(KEY,{}));load()}'''
suite=block(suite,'function jobCore(){','\nfunction digitalTwin(){',job_core)

jobs=jobs.replace("const KEY = 'print-prep-lab-jobs-v1';", "const KEY = 'print-prep-lab-jobs-v1';\n  const SELECTED_KEY = 'print-prep-lab-selected-job-id-v1';")
jobs=jobs.replace("function write(){try{localStorage.setItem(KEY,JSON.stringify(jobs));return true}catch{return false}}", "function write(){try{localStorage.setItem(KEY,JSON.stringify(jobs));return true}catch{return false}}\n  function selectedId(){return localStorage.getItem(SELECTED_KEY)||''}\n  function selectJob(id){if(id)localStorage.setItem(SELECTED_KEY,id);else localStorage.removeItem(SELECTED_KEY);renderJobs()}")
old="return `<article class=\"card\" data-id=\"${esc(j.id)}\"><div class=\"job-top\"><div><span class=\"kicker\">${esc(j.priority||'Normal')} priority</span><h3>${esc(j.name||'Untitled job')}</h3></div><span class=\"badge\">${done}/${STAGES.length} stages</span></div><p>${esc(j.product||'Product not set')}${j.provider?` · ${esc(j.provider)}`:''}</p><div class=\"job-meta\"><div><small>Quantity</small><b>${Number(j.quantity||1).toLocaleString()}</b></div><div><small>Due</small><b>${j.due?esc(j.due):'Not set'}</b></div><div><small>Readiness</small><b>${pct}%</b></div></div><div class=\"pipeline\">${STAGES.map(([k,l])=>`<button type=\"button\" class=\"step ${j.stages?.[k]?'done':(next?.[0]===k?'current':'')}\" data-stage=\"${k}\" title=\"Toggle ${l}\">${l}</button>`).join('')}</div>${j.notes?`<p>${esc(j.notes)}</p>`:''}<div class=\"job-actions\">${next?`<a class=\"btn primary\" href=\"${linkFor(next[0],j)}\">Next: ${next[1]}</a>`:'<span class=\"btn primary\" aria-label=\"All stages marked complete\">Ready for sign-off</span>'}<a class=\"btn\" href=\"/studio?job=${encodeURIComponent(j.name||'')}&provider=${encodeURIComponent(j.provider||'')}\">Studio</a><button class=\"btn\" type=\"button\" data-snapshot>Refresh snapshot</button><button class=\"btn danger\" type=\"button\" data-delete>Delete</button></div></article>`;"
new="const selected=selectedId()===j.id;return `<article class=\"card ${selected?'selected-job':''}\" data-id=\"${esc(j.id)}\"><div class=\"job-top\"><div><span class=\"kicker\">${esc(j.priority||'Normal')} priority</span><h3>${esc(j.name||'Untitled job')}</h3></div><span class=\"badge\">${selected?'SELECTED · ':''}${done}/${STAGES.length} stages</span></div><p>${esc(j.product||'Product not set')}${j.provider?` · ${esc(j.provider)}`:''}</p><div class=\"job-meta\"><div><small>Quantity</small><b>${Number(j.quantity||1).toLocaleString()}</b></div><div><small>Due</small><b>${j.due?esc(j.due):'Not set'}</b></div><div><small>Readiness</small><b>${pct}%</b></div></div><div class=\"pipeline\">${STAGES.map(([k,l])=>`<button type=\"button\" class=\"step ${j.stages?.[k]?'done':(next?.[0]===k?'current':'')}\" data-stage=\"${k}\" title=\"Toggle ${l}\">${l}</button>`).join('')}</div>${j.notes?`<p>${esc(j.notes)}</p>`:''}<div class=\"job-actions\"><button class=\"btn ${selected?'':'primary'}\" type=\"button\" data-select aria-pressed=\"${selected?'true':'false'}\">${selected?'Selected':'Select job'}</button><a class=\"btn\" href=\"/job-core\">Job Core</a>${next?`<a class=\"btn\" href=\"${linkFor(next[0],j)}\">Next: ${next[1]}</a>`:'<span class=\"btn\" aria-label=\"All stages marked complete\">Ready for sign-off</span>'}<a class=\"btn\" href=\"/studio?job=${encodeURIComponent(j.name||'')}&provider=${encodeURIComponent(j.provider||'')}\">Studio</a><button class=\"btn\" type=\"button\" data-snapshot>Refresh snapshot</button><button class=\"btn danger\" type=\"button\" data-delete>Delete</button></div></article>`;"
if old not in jobs: raise SystemExit('jobs card template marker not found')
jobs=jobs.replace(old,new)
jobs=jobs.replace("const stage=e.target.closest('[data-stage]');", "if(e.target.closest('[data-select]')){selectJob(j.id);return}\n    const stage=e.target.closest('[data-stage]');")
jobs=jobs.replace("if(e.target.closest('[data-delete]')){jobs=jobs.filter(x=>x.id!==j.id);write();renderJobs()}", "if(e.target.closest('[data-delete]')){jobs=jobs.filter(x=>x.id!==j.id);if(selectedId()===j.id)selectJob('');write();renderJobs()}")

repls={
'<div class="ep-eyebrow">Interactive module</div><h2>Job Core &amp; Revision Engine</h2><div class="ep-fields">':'<div class="ep-eyebrow">Interactive module</div><h2>Job Core &amp; Revision Engine</h2><div class="ep-note warn" id="ec-selected-job">No job selected.</div><div class="ep-fields">',
'<label>Job name<input id="ec-name" value="Sample print job"/></label>':'<label>Job name<input id="ec-name" placeholder="e.g. Gallery launch prints"/></label>',
'<label>Revision label<input id="ec-rev" value="R1"/></label>':'<label>Revision label<input id="ec-rev" placeholder="e.g. R1"/></label>',
'<label>Quantity<input id="ec-qty" min="1" type="number" value="500"/></label>':'<label>Quantity<input id="ec-qty" min="1" type="number" placeholder="e.g. 500"/></label>',
'<label>Trim size<input id="ec-size" value="210 × 297 mm"/></label>':'<label>Trim size<input id="ec-size" placeholder="e.g. 210 × 297 mm"/></label>',
'<label>Material<input id="ec-material" value="Coated stock"/></label>':'<label>Material<input id="ec-material" placeholder="e.g. Coated stock"/></label>',
'<label>Revision note<textarea id="ec-note">Initial production baseline</textarea></label>':'<label>Revision note<textarea id="ec-note" placeholder="Explain why this revision changed"></textarea></label>',
'<button class="ep-btn" id="ec-export">Export current job</button>':'<button class="ep-btn" id="ec-export">Export current job</button><a class="ep-btn" href="/jobs">Choose job</a>'
}
for a,b in repls.items():
    if a not in core_html: raise SystemExit('job-core html marker missing: '+a[:50])
    core_html=core_html.replace(a,b)

jobs_html=jobs_html.replace('<span class="kicker">v26 · Job intelligence</span><h2>Command center</h2>','<span class="kicker">Job workspace</span><h2>Job records</h2>')
jobs_html=jobs_html.replace('Create a local job record, snapshot the technical signals already in this browser, and see what is missing before production.','Create a local job record, select the job you are working on, and carry its identity into Job Core without replacing other saved jobs.')
jobs_html=jobs_html.replace('<div class="cards" id="jc-jobs"></div>','<div class="notice" style="margin:0 18px 4px">Select a job before opening Job Core. Selection is stored locally by job ID; switching jobs does not delete the other job.</div><div class="cards" id="jc-jobs"></div>')

suite_p.write_text(suite,encoding='utf-8')
jobs_js_p.write_text(jobs,encoding='utf-8')
jobs_html_p.write_text(jobs_html,encoding='utf-8')
core_html_p.write_text(core_html,encoding='utf-8')
print('Phase2c patched explicit selected jobs and non-destructive Job Core linkage')
