import fs from 'node:fs';
import vm from 'node:vm';
const code=fs.readFileSync(new URL('../release-artifacts/v119.1/enterprise-status-v1.js', import.meta.url),'utf8');
const ctx={window:{},document:{documentElement:{lang:'en'}}};vm.createContext(ctx);vm.runInContext(code,ctx);const R=ctx.window.PPLStatusRules;
const eq=(name,actual,expected)=>{if(actual!==expected)throw new Error(`${name}: expected ${expected}, got ${actual}`);console.log(`PASS ${name}: ${actual}`)};
eq('clean QA',R.evaluate('qa',null).state,'NO_DATA');
eq('QA zero',R.evaluate('qa',{total:0,pass:0,review:0,blocker:0}).state,'NO_DATA');
eq('QA blocker=0 completed',R.evaluate('qa',{total:3,pass:3,review:0,blocker:0,note:'FAIL is just free text'}).state,'PASS');
eq('QA real blocker',R.evaluate('qa',{total:3,pass:2,review:0,blocker:1,note:'all good'}).state,'BLOCK');
eq('QA review',R.evaluate('qa',{total:3,pass:2,review:1,blocker:0}).state,'REVIEW');
eq('QA invalid missing field',R.evaluate('qa',{total:3,pass:3,blocker:0}).state,'INVALID');
eq('QA free text ignored',R.evaluate('qa',{total:1,pass:1,review:0,blocker:0,finding:'BLOCK FAIL CRITICAL'}).state,'PASS');
eq('Preflight blocker field wins',R.evaluate('preflight',{state:'ready',blockers:1,warnings:0,note:'PASS'}).state,'BLOCK');
eq('Supplier intentionally unresolved',R.evaluate('supplier',{providers:[{name:'A',cap:90}],best:{name:'A'}}).state,'UNRESOLVED');
const mixed=[{result:R.evaluate('qa',{total:1,pass:1,review:0,blocker:0})},{result:R.evaluate('stock',{state:'SHORT'})}];eq('healthy source cannot cancel blocker',R.aggregate(mixed),'BLOCK');
eq('risk review',R.evaluate('risk',{total:2,open:1,high:0,review:1}).state,'REVIEW');
eq('stock reorder review',R.evaluate('stock',{state:'REORDER'}).state,'REVIEW');
eq('stock covered pass',R.evaluate('stock',{state:'COVERED'}).state,'PASS');
console.log('All Phase 2a status-rule cases passed.');
