import Link from "next/link";
import { PrintReadinessLab } from "@/components/print-readiness-lab";
import { GUIDE_PAGES, TOOL_PAGES } from "@/lib/site-content";
import { GUIDE_ARABIC } from "@/lib/source-arabic-guides";
import { TOOL_ARABIC } from "@/lib/source-arabic";
import { pageMetadata } from "@/lib/seo";
export const metadata = pageMetadata({title:"Print preparation, explained and calculated",description:"Check real pixels, print size, crop and bleed. Learn from worked printing examples and practical guides, with calculations that stay on your device.",path:"/"});
const cases = [
  {tag:"PHOTO / CROP",arTag:"صورة / قص",title:"A 3:2 photo in an 8 × 10 frame",arTitle:"صورة بنسبة 3:2 داخل إطار 8 × 10",detail:"A 6000 × 4000 photo becomes 5000 × 4000 pixels after a 5:4 fill crop. That is 500 PPI at 10 × 8 inches, with 16.7% of the original area removed.",arDetail:"تصبح صورة 6000 × 4000 بكسل بحجم 5000 × 4000 بعد قص ملء بنسبة 5:4. النتيجة 500 PPI عند طباعة 10 × 8 بوصات، مع فقد 16.7% من المساحة الأصلية.",href:"/guides/aspect-ratio-cropping-print",result:"500 PPI",note:"after crop",arNote:"بعد القص"},
  {tag:"FLYER / BLEED",arTag:"فلاير / نزف",title:"An A4 flyer with 3 mm bleed",arTitle:"فلاير A4 مع نزف 3 مم",detail:"The finished page is 210 × 297 mm. Adding 3 mm on all four edges makes a 216 × 303 mm canvas: 2551 × 3579 pixels at 300 PPI, rounded to whole pixels.",arDetail:"المقاس النهائي 210 × 297 مم. إضافة نزف 3 مم للحواف الأربع تعطي لوحة 216 × 303 مم: أي 2551 × 3579 بكسل عند 300 PPI بعد التقريب.",href:"/guides/bleed-trim-safe-area",result:"216 × 303",note:"mm artwork canvas",arNote:"مم للوحة التصميم"},
  {tag:"SOURCE / RESOLUTION",arTag:"المصدر / الدقة",title:"A small image, an honest print limit",arTitle:"صورة صغيرة وحد طباعة واقعي",detail:"A 1200 × 800 pixel original prints 4 × 2.67 inches at 300 PPI. Changing the file’s DPI tag cannot create the missing detail. A smaller print or a better source is the first fix.",arDetail:"صورة أصلية 1200 × 800 بكسل تطبع 4 × 2.67 بوصة عند 300 PPI. تغيير قيمة DPI لا يصنع التفاصيل الناقصة. ابدأ بمقاس أصغر أو مصدر أفضل.",href:"/guides/low-resolution-images-for-print",result:"4 × 2.67",note:"inches at 300 PPI",arNote:"بوصة عند 300 PPI"},
];
export default function Home(){return <main className="print-home">
  <section className="home-opening shell"><div><span className="home-label" data-en="PRINT PREP LAB / PRACTICAL PREPRESS" data-ar="PRINT PREP LAB / تجهيز عملي للطباعة">PRINT PREP LAB / PRACTICAL PREPRESS</span><h1><span data-en="Better print decisions." data-ar="قرارات طباعة أفضل.">Better print decisions.</span><em data-en="Start with the real pixels." data-ar="ابدأ بالبكسلات الحقيقية.">Start with the real pixels.</em></h1></div><div><p data-en="Check image resolution, final size, crop and bleed before sending your artwork to print. Use the calculation, understand what it means, then confirm the printer’s requirements." data-ar="افحص دقة الصورة والمقاس النهائي والقص والنزف قبل إرسال التصميم للطباعة. استخدم الحساب وافهم معناه، ثم أكّد متطلبات المطبعة.">Check image resolution, final size, crop and bleed before sending your artwork to print. Use the calculation, understand what it means, then confirm the printer’s requirements.</p><div className="home-intro-links"><Link href="/tools" data-en="Explore the seven tools" data-ar="استكشف الأدوات السبع">Explore the seven tools</Link><Link href="/guides" data-en="Learn the method" data-ar="تعلّم الطريقة">Learn the method</Link></div><div className="home-trust"><span data-en="Local image checks" data-ar="فحص الصور محليًا">Local image checks</span><span data-en="No account required" data-ar="بدون حساب">No account required</span><span data-en="Visible calculations" data-ar="حسابات واضحة">Visible calculations</span></div></div></section>
  <div className="shell home-calculator" id="workflow"><PrintReadinessLab /></div>
  <section className="home-tools shell"><div className="home-section-title"><div><span className="home-label" data-en="THE TOOLKIT" data-ar="الأدوات">THE TOOLKIT</span><h2 data-en="A tool for each print question." data-ar="أداة لكل سؤال عن الطباعة.">A tool for each print question.</h2></div><Link href="/tools" data-en="Compare all tools" data-ar="قارن الأدوات">Compare all tools</Link></div><div className="home-tool-grid">{TOOL_PAGES.map((tool,i)=><Link href={`/tools/${tool.slug}`} key={tool.slug}><span className="home-tool-number">{String(i+1).padStart(2,"0")}</span><h3 data-en={tool.shortTitle} data-ar={TOOL_ARABIC[tool.slug]?.shortTitle}>{tool.shortTitle}</h3><p data-en={tool.intent} data-ar={TOOL_ARABIC[tool.slug]?.intent}>{tool.intent}</p></Link>)}</div></section>
  <section className="home-cases"><div className="shell"><div className="home-section-title"><div><span className="home-label" data-en="WORKED EXAMPLES" data-ar="أمثلة محسوبة">WORKED EXAMPLES</span><h2 data-en="See the number. Understand the decision." data-ar="شاهد الرقم وافهم القرار.">See the number. Understand the decision.</h2></div><p data-en="Illustrative jobs with stated assumptions. Recalculate for your own printer and product." data-ar="مهام توضيحية بافتراضات معلنة. أعد الحساب حسب منتجك ومتطلبات مطبعتك.">Illustrative jobs with stated assumptions. Recalculate for your own printer and product.</p></div><div className="home-case-grid">{cases.map(c=><article key={c.title}><span className="home-label" data-en={c.tag} data-ar={c.arTag}>{c.tag}</span><h3 data-en={c.title} data-ar={c.arTitle}>{c.title}</h3><div className="home-case-result"><strong dir="ltr">{c.result}</strong><span data-en={c.note} data-ar={c.arNote}>{c.note}</span></div><p data-en={c.detail} data-ar={c.arDetail}>{c.detail}</p><Link href={c.href} data-en="Read the calculation and next steps" data-ar="اقرأ الحساب والخطوات التالية">Read the calculation and next steps</Link></article>)}</div></div></section>
  <section className="home-library shell"><div className="home-section-title"><div><span className="home-label" data-en="THE PRINT PREPARATION LIBRARY" data-ar="مكتبة تجهيز الطباعة">THE PRINT PREPARATION LIBRARY</span><h2 data-en="Go from an answer to a finished file." data-ar="انتقل من الإجابة إلى ملف جاهز.">Go from an answer to a finished file.</h2></div><p data-en="Learn resolution, cropping, color, export and production checks. Every guide links the decision to a practical next step." data-ar="تعلّم الدقة والقص والألوان والتصدير وفحوص الإنتاج. كل دليل يربط القرار بخطوة عملية.">Learn resolution, cropping, color, export and production checks. Every guide links the decision to a practical next step.</p></div><div className="home-guide-grid">{GUIDE_PAGES.map((g,i)=><Link key={g.slug} href={`/guides/${g.slug}`}><span>{String(i+1).padStart(2,"0")}</span><div><h3 data-en={g.title} data-ar={GUIDE_ARABIC[g.slug]?.heading}>{g.title}</h3><p data-en={g.description} data-ar={GUIDE_ARABIC[g.slug]?.description}>{g.description}</p></div></Link>)}</div></section>
  <section className="home-about shell"><div><span className="home-label" data-en="WHO THIS IS FOR" data-ar="لمن صُمم؟">WHO THIS IS FOR</span><h2 data-en="For the person preparing the print." data-ar="لمن يُجهّز الملف للطباعة.">For the person preparing the print.</h2></div><div><p data-en="Print Prep Lab helps designers, photographers, print sellers, students and production teams turn pixel dimensions and printer specifications into a repeatable preparation process. Start with a file or a finished size; the tools show the math rather than treating a DPI label as evidence of quality." data-ar="يساعد Print Prep Lab المصممين والمصورين وبائعي المطبوعات والطلاب وفرق الإنتاج على تحويل أبعاد البكسل ومواصفات المطبعة إلى خطوات تجهيز قابلة للتكرار. ابدأ بملف أو مقاس نهائي؛ الأدوات تعرض الحساب ولا تعتبر قيمة DPI دليلًا على الجودة.">Print Prep Lab helps designers, photographers, print sellers, students and production teams turn pixel dimensions and printer specifications into a repeatable preparation process. Start with a file or a finished size; the tools show the math rather than treating a DPI label as evidence of quality.</p><p data-en="A pixel-density result is one check, not a production approval. Sharpness, compression, color profiles, fonts, paper and finishing need separate review. Our guides explain these limits and help you ask the printer the right questions." data-ar="نتيجة كثافة البكسل فحص واحد وليست اعتمادًا للإنتاج. الحدة والضغط وملفات اللون والخطوط والورق والتشطيب تحتاج مراجعة مستقلة. أدلتنا تشرح الحدود وتساعدك على توجيه الأسئلة المناسبة للمطبعة.">A pixel-density result is one check, not a production approval. Sharpness, compression, color profiles, fonts, paper and finishing need separate review. Our guides explain these limits and help you ask the printer the right questions.</p><nav><Link href="/methodology" data-en="Our calculation methodology" data-ar="منهجية الحساب">Our calculation methodology</Link><Link href="/sources" data-en="Sources and references" data-ar="المصادر والمراجع">Sources and references</Link></nav></div></section>
  <section className="home-workspace shell"><div><h2 data-en="Managing a production job?" data-ar="تدير مهمة إنتاج؟">Managing a production job?</h2><p data-en="Keep browser-local jobs, costing, suppliers and release evidence together in the professional workspace." data-ar="اجمع المهام المحلية والتكلفة والموردين وأدلة الإصدار في مساحة العمل الاحترافية.">Keep browser-local jobs, costing, suppliers and release evidence together in the professional workspace.</p></div><Link className="button secondary" href="/workspace" data-en="Open the workspace" data-ar="افتح مساحة العمل">Open the workspace</Link></section>
</main>}
