import type { GuidePage } from "@/lib/site-content";

export const ADDITIONAL_GUIDES: GuidePage[] = [
  {
    slug: "print-file-preflight-checklist",
    title: "Print File Preflight Checklist: 12 Checks Before You Export",
    heading: "A Practical Print File Preflight Checklist",
    description: "Check trim, crop, effective PPI, bleed, safe area, color, file format and proofing in the right order before sending artwork to print.",
    takeaway: "Lock the product specification first, then verify geometry, pixels and production settings in that order.",
    quickAnswer: "A useful preflight is more than a 300 PPI check. Confirm the finished trim and orientation, position the final crop, calculate effective PPI from the pixels that remain, add the provider's bleed and safe margin, then verify color, file format, fonts and proofing instructions.",
    formula: "specification → crop → effective PPI → bleed → export → proof",
    summary: [
      { label: "Geometry", value: "Trim + crop", note: "Fix the final size and composition first" },
      { label: "Raster detail", value: "Effective PPI", note: "Calculate from usable post-crop pixels" },
      { label: "Production", value: "Provider spec", note: "Bleed, color and export rules are product specific" },
    ],
    comparison: {
      caption: "What to verify at each preflight stage",
      headers: ["Stage", "Question", "Evidence", "Common failure"],
      rows: [
        ["Product", "What exact item is being printed?", "Written provider specification", "Using a generic size or bleed"],
        ["Composition", "Will the image fill or fit?", "Final crop preview", "Faces or text cut at the edge"],
        ["Resolution", "How many pixels remain per inch?", "Horizontal and vertical effective PPI", "Trusting a metadata tag"],
        ["Document", "Where are trim, bleed and safe area?", "Visible document boxes", "Adding bleed to only one edge"],
        ["Export", "Does the file match the workflow?", "Provider format and color instructions", "Guessing PDF, JPEG or CMYK settings"],
      ],
    },
    sections: [
      { heading: "Start with the product specification, not the artwork", paragraphs: ["Write down the finished trim size, orientation, bleed on each edge, safe margin, preferred file format, color profile and minimum or recommended image PPI. A business card, photo print, paperback cover and trade-show panel can all use different rules even when their physical dimensions appear similar.", "If the provider offers a template, use that template as the geometry authority. Generic defaults such as 3 mm bleed or 300 PPI are useful examples, but they do not override the instructions for the product you are buying."] },
      { heading: "Lock trim, orientation and crop before judging resolution", paragraphs: ["Trim is the finished cut size. Decide portrait or landscape, then choose whether the image will fill the page, fit inside it with borders, or sit within a designed layout. A ratio mismatch changes the crop and therefore changes the number of usable pixels.", "For example, a 6000 × 4000 px 3:2 image filling a 16 × 20 inch 4:5 frame retains about 5000 × 4000 px. The final density is therefore 250 PPI in both directions, not the 300 PPI someone might infer by dividing the original 6000-pixel edge by 20 inches."] },
      { heading: "Calculate effective PPI from the final usable pixels", paragraphs: ["Divide the post-crop pixel width by the printed width in inches and repeat for height. Use the lower result as the limiting effective PPI. This calculation answers whether the raster contains enough source pixels for the selected target.", "Do not substitute file size in megabytes or the 72/300 value stored in metadata. Compression, layers and format change megabytes; a metadata tag changes suggested scale. Neither creates captured detail. Inspect focus and compression separately because a numerically dense but blurred image can still print poorly."] },
      { heading: "Build bleed and protect the safe area", paragraphs: ["Extend edge-to-edge backgrounds beyond the trim by the provider's bleed value. Bleed is added to both sides of each dimension: an A4 trim at 210 × 297 mm with 3 mm bleed becomes a 216 × 303 mm canvas. It does not make the finished piece larger.", "Keep text, logos, faces and other critical details inside the safe margin. The safe area is not a guarantee against every finishing variation; it is a deliberate buffer inside the trim. Fold lines, binding, perforation and rounded corners may need additional product-specific protection."] },
      { heading: "Verify export, color and proofing without guessing", paragraphs: ["Follow the provider's requested file type, color profile, transparency, font and compression settings. Converting every file to CMYK or flattening every PDF is not automatically correct; some services request sRGB JPEG files while others supply a specific PDF and CMYK workflow.", "Open the exported file again, check its final dimensions and page count, zoom into edges and small text, and confirm that no crop or bleed guides were accidentally exported as artwork. For important jobs, order a physical proof or the provider's closest equivalent before committing to the full run."] },
      { heading: "Use a repeatable twelve-point sign-off", paragraphs: ["Before delivery, confirm: product, trim, orientation, crop, usable pixels, effective PPI, bleed, safe area, color instructions, file format, embedded or outlined fonts where required, and proof approval. Record the provider specification beside the exported file so a later revision uses the same assumptions.", "A checklist cannot remove every production variable, but it prevents the most common category error: solving the right calculation for the wrong final product."] },
    ],
    workflow: ["Save the provider's specification and template for the exact product.", "Fix trim, orientation and the final fill-or-fit crop.", "Calculate effective PPI from the post-crop pixels.", "Add bleed, protect the safe area, export to specification and inspect the exported file."],
    mistakes: ["Checking resolution before the final crop", "Using a generic bleed value without reading the product specification", "Assuming CMYK, PDF or 300 PPI is mandatory for every provider", "Skipping a reopened-file check or physical proof for an important run"],
    faq: [
      { question: "What is the first thing to check before exporting a print file?", answer: "Confirm the exact product specification: finished trim, orientation, bleed, safe margin, resolution, color profile and file type. Every later calculation depends on those values." },
      { question: "Should I check PPI before or after cropping?", answer: "After cropping. A fill crop removes pixels, so effective PPI must use the remaining pixel width and height." },
      { question: "Do I need to convert every print file to CMYK?", answer: "No. Use the provider's color instructions. Some workflows request a supplied CMYK profile; others expect sRGB and perform conversion themselves." },
      { question: "Does a passed preflight guarantee the print?", answer: "No. It verifies the file against known requirements, but paper, ink, calibration, finishing tolerance and viewing conditions still affect the product. Use a proof for critical work." },
      { question: "Should crop marks be included in the exported artwork?", answer: "Only when the provider specifically requests them. Many online services use PDF page boxes or a supplied template and do not want visible marks inside the submitted page." },
    ],
    related: ["how-large-can-i-print-my-image", "bleed-trim-safe-area", "print-resolution-guide"],
    primaryCta: { label: "Run the print readiness check", href: "/tools/print-readiness-checker" },
    sources: [
      { label: "Adobe Photoshop — Image size and resolution", href: "https://helpx.adobe.com/photoshop/using/image-size-resolution.html" },
      { label: "Print Prep Lab calculation methodology", href: "/methodology" },
      { label: "Print Prep Lab sources and reference policy", href: "/sources" },
    ],
  },
  {
    slug: "export-images-for-large-format-printing",
    title: "How to Export Images for Large-Format Printing",
    heading: "Prepare and Export an Image for a Large Print",
    description: "Choose dimensions, viewing-distance resolution, crop, sharpening, color and export settings for posters and wall prints without inventing pixels.",
    takeaway: "Judge a large print at its final size and normal viewing distance, then export to the provider's exact workflow.",
    quickAnswer: "For a large print, start with the finished size and viewing distance. Apply the final crop, calculate effective PPI from the pixels that remain, inspect the source at an appropriate scale, then follow the provider's color, file-format and sharpening instructions. Do not enlarge merely by changing the DPI metadata field.",
    formula: "effective PPI = post-crop pixels ÷ final printed inches",
    summary: [
      { label: "Close viewing", value: "More detail", note: "Small text and fine texture need a denser source" },
      { label: "Far viewing", value: "Lower PPI may work", note: "The provider still decides the accepted minimum" },
      { label: "Export", value: "One final file", note: "Keep the editable source and follow the requested profile" },
    ],
    comparison: {
      caption: "Example requirements for a 24 × 36 inch print",
      headers: ["Planning target", "Required pixels", "Approx. megapixels", "What to verify"],
      rows: [
        ["300 PPI", "7200 × 10800", "77.8 MP", "Close detail and provider acceptance"],
        ["240 PPI", "5760 × 8640", "49.8 MP", "Strong photographic detail when accepted"],
        ["150 PPI", "3600 × 5400", "19.4 MP", "Longer viewing distance and source quality"],
      ],
    },
    sections: [
      { heading: "Define the final size and where it will be viewed", paragraphs: ["A 24 × 36 inch framed photograph examined from two feet away is a different job from a display panel viewed across a room. Record the trim, orientation, expected viewing distance and whether the image must cover the entire surface.", "Ask the provider for a recommended and minimum raster resolution. Do not infer the required image PPI from the printer's advertised hardware DPI; multiple output dots may reproduce one image pixel."] },
      { heading: "Crop at the delivery ratio before calculating", paragraphs: ["A common camera image uses 3:2, which fits a 24 × 36 inch print directly. A 4:5 wall print needs a different crop. Position the composition first because every removed edge also removes pixels available for the enlargement.", "If cropping would damage the image, choose a ratio-friendly product, fit the complete image with a border, or design an intentional background rather than stretching the subject."] },
      { heading: "Choose a defensible PPI target", paragraphs: ["Multiply the print dimensions in inches by the accepted PPI to find the required export pixels. At 24 × 36 inches, 300 PPI needs 7200 × 10800 px, 240 PPI needs 5760 × 8640 px and 150 PPI needs 3600 × 5400 px.", "Lower PPI can be appropriate for some large, distant-viewed products, but it is not permission to ignore source quality. Fine text, line work, heavy compression and missed focus remain visible in ways a simple pixel count cannot predict."] },
      { heading: "Resample deliberately and keep the original", paragraphs: ["Changing only a resolution metadata tag does not add pixels. Actual upsampling creates estimated pixels. Modern resampling can smooth an enlargement, but it cannot recover detail that the camera or original artwork never captured.", "Keep an untouched master, finish retouching and crop at full quality, then create one delivery copy at the required dimensions. Evaluate sharpening on that copy because output sharpening depends on final size, material and print process."] },
      { heading: "Treat text and graphics differently from photographs", paragraphs: ["When the workflow supports PDF, keep logos, typography and line art as vector objects so they are not limited by the photo's raster PPI. Avoid flattening vector elements into a needlessly low-resolution image early in the process.", "Small text, QR codes and thin lines deserve a provider proof. A photographic image that looks acceptable at a lower PPI does not mean every overlaid design element will reproduce equally well."] },
      { heading: "Export to the provider's color and file specification", paragraphs: ["Use the requested profile and file type. Some photographic labs want sRGB JPEG files; some commercial workflows supply a CMYK ICC profile and PDF preset. A generic conversion can create avoidable color shifts or double conversion.", "Reopen the exported file, confirm its exact pixel dimensions, inspect compression and gradients, and verify that it contains the intended crop and no hidden guide layers. Order a proof for color-critical or expensive work."] },
    ],
    workflow: ["Record the final size, ratio, viewing distance and provider requirements.", "Apply the final crop and calculate the remaining effective PPI.", "Resample only when necessary, then sharpen for the final output size.", "Export with the requested color profile and file type, reopen it and proof the result."],
    mistakes: ["Changing the DPI metadata tag and assuming the file gained detail", "Using the uncropped pixel count", "Rasterizing text and logos too early", "Converting to a guessed color profile instead of the provider's requested profile"],
    faq: [
      { question: "Is 150 PPI enough for a large poster?", answer: "It may be suitable for some large prints viewed farther away, but the provider's minimum, the image content and the viewing distance decide. Fine text and close viewing are less forgiving." },
      { question: "Should I export a large print as JPEG or PDF?", answer: "Use the provider's requested format. Photo labs often accept high-quality JPEG, while layouts with vector text, page boxes or a supplied preset may require PDF." },
      { question: "Does AI upscaling create real original detail?", answer: "No. It estimates new pixels and can improve appearance in some images, but it cannot recover information that was never captured or guarantee a printer-specific result." },
      { question: "Should I sharpen before or after resizing?", answer: "Keep a clean master, then evaluate output sharpening after the image is at its final delivery dimensions. Follow the provider's guidance when it offers a product-specific workflow." },
    ],
    related: ["print-resolution-guide", "how-large-can-i-print-my-image", "print-file-preflight-checklist"],
    primaryCta: { label: "Calculate maximum print size", href: "/tools/pixels-to-print-size" },
    sources: [
      { label: "Adobe Photoshop — Image size and resolution", href: "https://helpx.adobe.com/photoshop/using/image-size-resolution.html" },
      { label: "Adobe — Resolution specifications for printing images", href: "https://helpx.adobe.com/photoshop/desktop/crop-resize-transform/resize-adjust-resolution/resolution-specs-for-printing-images.html" },
      { label: "Print Prep Lab calculation methodology", href: "/methodology" },
    ],
  },
  {
    slug: "a4-vs-us-letter-printing",
    title: "A4 vs US Letter: Size, Pixels and Layout Differences",
    heading: "A4 vs US Letter for Printing and Layout",
    description: "Compare A4 and US Letter in millimetres, inches, pixels and aspect ratio, then adapt a full-page layout without accidental crop or reflow.",
    takeaway: "Letter is wider and shorter than A4, so a full-page design should be reflowed or fitted—not silently stretched.",
    quickAnswer: "A4 is 210 × 297 mm; US Letter is 8.5 × 11 inches, or 215.9 × 279.4 mm. In portrait, Letter is 5.9 mm wider and 17.6 mm shorter. At 300 PPI, A4 rounds to 2480 × 3508 px while Letter is exactly 2550 × 3300 px.",
    formula: "fit scale = smaller of target width ratio and target height ratio",
    summary: [
      { label: "A4", value: "210 × 297 mm", note: "ISO 216 format with a 1:√2 ratio" },
      { label: "US Letter", value: "8.5 × 11 in", note: "215.9 × 279.4 mm with a 17:22 ratio" },
      { label: "Difference", value: "+5.9 / −17.6 mm", note: "Letter is wider and shorter in portrait" },
    ],
    comparison: {
      caption: "A4 and US Letter at common print resolutions",
      headers: ["Format", "Physical trim", "Pixels at 300 PPI", "Layout effect"],
      rows: [
        ["A4", "210 × 297 mm", "2480 × 3508", "Taller, slightly narrower page"],
        ["US Letter", "8.5 × 11 in", "2550 × 3300", "Wider, noticeably shorter page"],
        ["A4 fitted on Letter", "Scale to about 94.1%", "Depends on source", "Side margins remain"],
        ["Letter fitted on A4", "Scale to about 97.3%", "Depends on source", "Top and bottom margins remain"],
      ],
    },
    sections: [
      { heading: "The formats are close, but not interchangeable", paragraphs: ["A4 belongs to the ISO A-series and measures 210 × 297 mm. US Letter measures 8.5 × 11 inches, exactly 215.9 × 279.4 mm. Letter gains 5.9 mm across the short edge but loses 17.6 mm along the long edge.", "That difference is enough to change page breaks, move a footer, crop a full-bleed background or leave uneven borders. Selecting Letter in a print dialog does not automatically redesign an A4 document."] },
      { heading: "Their aspect ratios explain the crop", paragraphs: ["A4 has the ISO 1:√2 proportion, approximately 0.707 in portrait width-to-height terms. Letter is 17:22, approximately 0.773. Letter therefore appears wider relative to its height.", "Filling one format with artwork designed for the other requires a crop. Fitting preserves the complete page but leaves margin space. Stretching changes shapes, typography and logos and is normally the least defensible choice."] },
      { heading: "Pixel dimensions depend on PPI", paragraphs: ["At 300 PPI, A4 rounds to 2480 × 3508 px because its metric dimensions convert to non-integer inches. Letter is exactly 2550 × 3300 px because its physical definition is already in inches. At 150 PPI, the corresponding values are 1240 × 1754 px and 1275 × 1650 px.", "Those are trim dimensions. Add the provider's bleed after choosing the format: an A4 canvas with 3 mm bleed is 216 × 303 mm, while Letter with 0.125 inch bleed becomes 8.75 × 11.25 inches."] },
      { heading: "Adapt documents by reflowing or fitting intentionally", paragraphs: ["For editable documents, change the page size, inspect every page break, reposition full-page elements and verify headers, footers and tables. This preserves readable type and uses the new page area deliberately.", "For a fixed PDF or image, choose fit when every element must remain visible, or crop only after previewing the exact lost area. A4 fitted within Letter is limited by Letter's shorter height and scales to roughly 94.1%, leaving side margins. Results can vary with printer non-printable margins."] },
      { heading: "Choose the format for the audience and printer", paragraphs: ["A4 is the normal office and publication format in most countries using the ISO system. US Letter is common for North American office documents, forms and home printers. The correct choice is the format the recipient and production service actually expect.", "When one file must serve both audiences, design with generous internal margins and avoid placing critical elements close to any edge. Export and inspect both versions rather than relying on a viewer's automatic shrink-to-fit setting."] },
    ],
    workflow: ["Identify the recipient's required paper format.", "Change the editable page size or choose fit for a fixed file.", "Inspect page breaks, edge elements, borders and full-bleed artwork.", "Recalculate pixels and bleed for the selected final format before export."],
    mistakes: ["Treating A4 and Letter as two names for the same page", "Stretching one ratio into the other", "Using a 300 PPI trim table as a bleed canvas", "Ignoring the printer's non-printable margin on office devices"],
    faq: [
      { question: "Is A4 the same as 8.5 × 11 inch paper?", answer: "No. A4 is 210 × 297 mm; 8.5 × 11 is US Letter at 215.9 × 279.4 mm. Letter is wider and shorter in portrait." },
      { question: "Will an A4 PDF be cut off on Letter paper?", answer: "It can be if printed at actual size. Fit-to-page preserves the full A4 page but reduces it and leaves margins. Always inspect the print preview." },
      { question: "How many pixels are A4 and Letter at 300 PPI?", answer: "Portrait A4 rounds to 2480 × 3508 px. Portrait US Letter is exactly 2550 × 3300 px. Neither value includes bleed." },
      { question: "Which format should I design first?", answer: "Use the format required by the main recipient or printer. If both are needed, maintain two checked layouts or use generous margins that tolerate intentional fitting." },
    ],
    related: ["print-file-preflight-checklist", "bleed-trim-safe-area", "print-resolution-guide"],
    primaryCta: { label: "Compare paper pixel sizes", href: "/tools/paper-size-pixels-calculator" },
    sources: [
      { label: "ISO 216:2007 paper formats", href: "https://www.iso.org/standard/36631.html" },
      { label: "NIST — SI units and the exact inch conversion", href: "https://www.nist.gov/pml/owm/si-units-length" },
      { label: "Print Prep Lab A4 reference", href: "/sizes/a4" },
      { label: "Print Prep Lab US Letter reference", href: "/sizes/us-letter" },
    ],
  },
];
