import { FEATURED_SIZE_CONTENT } from "@/lib/size-editorial-content";
import { SIZE_ARABIC, sizeArabicQuickAnswer } from "@/lib/size-arabic";
import { SizeWorkshop } from "@/components/size-workshop";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, FaqList, PageCta, PageHero } from "@/components/content-shell";
import { ToolCalculator } from "@/components/tool-calculators";
import { PRINT_PRESETS, formatDecimal, mmToInches, pixelsForMm } from "@/lib/print-math";
import { SIZE_DETAILS, SIZE_USE_CASES } from "@/lib/site-content";
import { pageMetadata } from "@/lib/seo";

const ppiRows = [72, 96, 150, 240, 300, 600];

export function generateStaticParams() { return PRINT_PRESETS.map((preset) => ({ slug: preset.slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const preset = PRINT_PRESETS.find((item) => item.slug === slug);
  const featured = FEATURED_SIZE_CONTENT[slug];
  return preset ? pageMetadata({ title: featured?.seoTitle ?? `${preset.shortLabel} Size in Pixels, Inches, CM & MM`, description: featured?.metaDescription ?? `${preset.label} dimensions and pixel sizes at 72, 96, 150, 240, 300 and 600 PPI, with aspect ratio and print setup guidance.`, path: `/sizes/${slug}` }) : {};
}

export default async function SizeDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const preset = PRINT_PRESETS.find((item) => item.slug === slug);
  if (!preset) notFound();
  const detail = SIZE_DETAILS[preset.slug];
  const useCase = SIZE_USE_CASES[preset.slug];
  const ar = SIZE_ARABIC[preset.slug];
  const featured = FEATURED_SIZE_CONTENT[preset.slug];
  const widthIn = mmToInches(preset.widthMm);
  const heightIn = mmToInches(preset.heightMm);
  const faq = [
    { question: `What is ${preset.shortLabel} at 300 PPI?`, answer: `${preset.shortLabel} in portrait orientation is ${pixelsForMm(preset.widthMm, 300)} × ${pixelsForMm(preset.heightMm, 300)} pixels at 300 PPI. Landscape uses the same two values in reverse order.`, questionAr: `كم بكسل يحتاج ${preset.shortLabel} عند 300 PPI؟`, answerAr: `${preset.shortLabel} في الوضع الرأسي يحتاج ${pixelsForMm(preset.widthMm,300)} × ${pixelsForMm(preset.heightMm,300)} بكسل عند 300 PPI. الوضع الأفقي يستخدم القيم نفسها بترتيب معكوس.` },
    { question: `What aspect ratio is ${preset.shortLabel}?`, answer: `${preset.shortLabel} uses a ${detail.ratio} aspect ratio. An image with a different ratio must be cropped, fitted with borders or placed inside the page.`, questionAr: `ما نسبة أبعاد ${preset.shortLabel}؟`, answerAr: `يستخدم ${preset.shortLabel} نسبة ⁦${detail.ratio}⁩. الصورة بنسبة مختلفة تحتاج القص أو الاحتواء مع حدود أو وضعها داخل تصميم الصفحة.` },
    { question: `Does the ${preset.shortLabel} pixel size include bleed?`, answer: "No. The table uses final trim dimensions. Add the exact bleed required by the printer to both sides before calculating the full artwork canvas.", questionAr: `هل عدد بكسلات ${preset.shortLabel} يشمل النزف؟`, answerAr: "لا. يعتمد الجدول مقاس التشذيب النهائي. أضف نزف المطبعة المطلوب على جانبي كل بعد قبل حساب لوحة التصميم الكاملة." },
    ...(featured ? [{...featured.extraFaq, questionAr: ar.extraFaq.question, answerAr: ar.extraFaq.answer}] : []),
  ];
  return <main><div className="shell"><Breadcrumbs items={[{ label: "Home", arLabel: "الرئيسية", href: "/" }, { label: "Print sizes", arLabel: "مقاسات الطباعة", href: "/sizes" }, { label: preset.shortLabel, arLabel: ar.label }]} /></div>
    <PageHero eyebrow={`${preset.group} size reference`} arEyebrow={preset.group === "Photo" ? "مرجع مقاس صورة" : "مرجع مقاس ورق"} title={featured?.heading ?? `${preset.shortLabel} size in pixels, inches, cm & mm`} arTitle={`${ar.label}: الأبعاد الفعلية وعدد البكسلات`} description={`${preset.label} measures ${formatDecimal(preset.widthMm, 1)} × ${formatDecimal(preset.heightMm, 1)} mm. Its pixel dimensions change with PPI; the physical trim size does not.`} arDescription={`${ar.label} يقيس ${preset.widthMm} × ${preset.heightMm} مم. يتغير عدد البكسلات مع PPI، بينما يظل مقاس التشذيب الفعلي ثابتًا.`}><div className="dimension-card"><span>{preset.shortLabel}</span><strong dir="ltr" data-en={`${formatDecimal(preset.widthMm,1)} × ${formatDecimal(preset.heightMm,1)} mm`} data-ar={`${preset.widthMm} × ${preset.heightMm} مم`}>{formatDecimal(preset.widthMm, 1)} × {formatDecimal(preset.heightMm, 1)} mm</strong><b dir="ltr" data-en={`${formatDecimal(widthIn)} × ${formatDecimal(heightIn)} in`} data-ar={`${formatDecimal(widthIn)} × ${formatDecimal(heightIn)} بوصة`}>{formatDecimal(widthIn)} × {formatDecimal(heightIn)} in</b><small><span data-en="Aspect ratio" data-ar="نسبة الأبعاد">Aspect ratio</span> <bdi dir="ltr" data-aspect-ratio>{detail.ratio}</bdi></small></div></PageHero>
    {featured && <section className="quick-answer shell" aria-label={`${preset.shortLabel} quick answer`}><div><span data-en="Quick answer" data-ar="إجابة سريعة">Quick answer</span><p data-en={featured.quickAnswer} data-ar={sizeArabicQuickAnswer(preset)}>{featured.quickAnswer}</p></div><code data-en={featured.formulaLine} data-ar={`300 PPI: ${pixelsForMm(preset.widthMm,300)} × ${pixelsForMm(preset.heightMm,300)} بكسل · التشذيب فقط`}>{featured.formulaLine}</code></section>}
    <section className="content-section shell size-detail-grid"><article><div className="section-kicker" data-en="Pixel table" data-ar="جدول البكسلات">Pixel table</div><h2 data-en={`${preset.shortLabel} pixels by PPI`} data-ar={`عدد بكسلات ${preset.shortLabel} حسب PPI`}>{preset.shortLabel} pixels by PPI</h2><p data-en="Portrait values are rounded to the nearest whole pixel after converting the native physical dimensions." data-ar="تُقرّب قيم الوضع الرأسي إلى أقرب بكسل كامل بعد تحويل الأبعاد الفعلية الأصلية.">Portrait values are rounded to the nearest whole pixel after converting the native physical dimensions.</p><div className="data-table-wrap"><table className="data-table"><thead><tr><th>PPI</th><th data-en="Width" data-ar="العرض">Width</th><th data-en="Height" data-ar="الارتفاع">Height</th><th data-en="Use context" data-ar="سياق الاستخدام">Use context</th></tr></thead><tbody>{ppiRows.map((ppi) => <tr key={ppi}><td><b>{ppi}</b></td><td dir="ltr" data-en={`${pixelsForMm(preset.widthMm,ppi)} px`} data-ar={`${pixelsForMm(preset.widthMm,ppi)} بكسل`}>{pixelsForMm(preset.widthMm, ppi)} px</td><td dir="ltr" data-en={`${pixelsForMm(preset.heightMm,ppi)} px`} data-ar={`${pixelsForMm(preset.heightMm,ppi)} بكسل`}>{pixelsForMm(preset.heightMm, ppi)} px</td><td data-en={ppi >= 300 ? "Detailed print target" : ppi >= 150 ? "Print / distance dependent" : "Layout or screen reference"} data-ar={ppi >= 300 ? "هدف لطباعة دقيقة" : ppi >= 150 ? "يعتمد على الطباعة ومسافة المشاهدة" : "مرجع للتخطيط أو الشاشة"}>{ppi >= 300 ? "Detailed print target" : ppi >= 150 ? "Print / distance dependent" : "Layout or screen reference"}</td></tr>)}</tbody></table></div></article><aside><div className="fact-panel"><span data-en="Common uses" data-ar="استخدامات شائعة">Common uses</span><p data-en={`${detail.uses}.`} data-ar={`${ar.uses}.`}>{detail.uses}.</p><span data-en="Print note" data-ar="ملاحظة طباعة">Print note</span><p data-en={detail.note} data-ar={ar.note}>{detail.note}</p><Link href="/tools/aspect-ratio-crop-preview" data-en="Preview a crop" data-ar="عاين القص">Preview a crop</Link></div></aside></section>
    {featured && <section className="size-insights shell" aria-label={`${preset.shortLabel} planning notes`}>{featured.insights.map((item,i) => <article key={item.heading}><span data-en={item.label} data-ar={ar.insights[i].label}>{item.label}</span><h2 data-en={item.heading} data-ar={ar.insights[i].heading}>{item.heading}</h2><p data-en={item.text} data-ar={ar.insights[i].text}>{item.text}</p>{item.href && item.linkLabel && <Link href={item.href} data-en={item.linkLabel} data-ar={ar.insights[i].linkLabel}>{item.linkLabel}</Link>}</article>)}</section>}
    {useCase && <section className="size-use-case shell" aria-labelledby={`${preset.slug}-use-case-heading`}><div><div className="section-kicker" data-en="Format-specific context" data-ar="شرح خاص بهذا المقاس">Format-specific context</div><h2 id={`${preset.slug}-use-case-heading`} data-en={useCase.heading} data-ar={ar.useCase.heading}>{useCase.heading}</h2></div><article>{useCase.paragraphs.map((paragraph,i) => <p key={paragraph} data-en={paragraph} data-ar={ar.useCase.paragraphs[i]}>{paragraph}</p>)}</article></section>}
    <SizeWorkshop preset={preset} />
    <section className="tool-embed shell"><div className="section-kicker" data-en="Change the resolution" data-ar="غيّر الدقة">Change the resolution</div><h2 data-en={`Calculate ${preset.shortLabel} at any PPI.`} data-ar={`احسب ${preset.shortLabel} عند أي قيمة PPI.`}>Calculate {preset.shortLabel} at any PPI.</h2><ToolCalculator mode="paper-size-pixels-calculator" initialPreset={preset.slug} /></section>
    <section className="content-section shell two-column-copy"><article><div className="section-kicker" data-en="Print setup" data-ar="تجهيز الطباعة">Print setup</div><h2 data-en="Trim first. Add production values second." data-ar="حدد التشذيب أولًا، ثم أضف قيم الإنتاج.">Trim first. Add production values second.</h2><p data-en={`${preset.shortLabel} identifies the final physical format. Bleed expands the artwork beyond that edge; a safe margin moves important content inward. Those extra values depend on the print provider.`} data-ar={`يحدد ${preset.shortLabel} المقاس الفعلي النهائي. يوسّع النزف التصميم خارج الحافة، بينما يبعد هامش الأمان المحتوى المهم إلى الداخل. هذه القيم الإضافية تعتمد على مزود الطباعة.`}>{preset.shortLabel} identifies the final physical format. Bleed expands the artwork beyond that edge; a safe margin moves important content inward. Those extra values depend on the print provider.</p><Link className="text-link" href="/tools/bleed-safe-area-calculator" data-en="Calculate bleed and safe area" data-ar="احسب النزف ومنطقة الأمان">Calculate bleed and safe area</Link></article><aside><div className="section-kicker" data-en={`Questions about ${preset.shortLabel}`} data-ar={`أسئلة عن ${preset.shortLabel}`}>Questions about {preset.shortLabel}</div><FaqList items={faq} /></aside></section>
    <div className="shell"><PageCta eyebrow={`${preset.shortLabel} file check`} arEyebrow={`فحص ملف ${preset.shortLabel}`} title={`Check whether your image fits ${preset.shortLabel}.`} arTitle={`تحقق هل تناسب صورتك ${preset.shortLabel}.`} description={`Use the source pixels, final orientation and intended crop for ${detail.uses}; then confirm the required PPI with the provider.`} arDescription={`استخدم بكسلات المصدر والاتجاه النهائي والقص المقصود من أجل ${ar.uses}، ثم أكد PPI المطلوب مع المزود.`} /></div>
  </main>;
}
